### ISSUE TITLE
powershell automated install SSL/TLS error

### ISSUE THREAD

**Issue by mastahcez** [ConEmu/ConEmu.github.io#23]
The command for automated install of ConEmu stopped working for me yesterday.

powershell -NoProfile -ExecutionPolicy Unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://conemu.github.io/install.ps1'))"

Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
At line:1 char:1
+ iex ((new-object net.webclient).DownloadString('https://conemu.github.io/install ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

-------------------------------------------------------------------------------------------------------------------
I don't know if github changed something or it's on my side but it works fine if I set the security protocol to tls 1.2 like so:

powershell -NoProfile -ExecutionPolicy Unrestricted -Command "ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; iex ((new-object net.webclient).DownloadString('https://conemu.github.io/install.ps1'))"

**Comment by ConEmu** [comment]
Just fixed
