### ISSUE TITLE
Тормозит bash + ssh

### ISSUE THREAD

**Issue by PavelApostol** [ConEmu/ConEmu.github.io#24]
Я сегодня подумал что у меня виртуальная машина глючит, подключаюсь к ней по ssh, открываю файл, оно задумывается на пару секунд, закрываю файл, оно опять мигает курсором, потом показывает консоль.
Это происходит только если выбрать shell bash, дальше я открыл в новой вкладке просто cmd, а в нем набрал команду bash, подключился по ssh и всё летает.
Дальше я добавил свой shell в настройках, прописав там %windir%\bash.exe и всё залетало, могу даже видео снять, у меня последняя альфа стоит 64 битная на windows 10.
Ваш bash идет через какой то собственный cygwin, который выступает транспортом к WSL?

Проблемы отмечаются именно при открытии полноэкранных приложений в консоли типа там nano. Выглядит это так, как будто у меня на сервере жесткий диск умирает или интернет глючит, ну в общем терминал замирает при обновлении.

**Comment by Maximus5** [comment]
Этот трекер предназначен *только* для внесения изменений в документацию.
ConEmu запускает wslbridge для работы с WSL. Я сомневаюсь, что проблема может быть на стороне ConEmu.
Для дальнейшего обсуждения проблемы создайте правильный [issue](https://conemu.github.io/en/Issues.html).

* https://conemu.github.io/en/BashOnWindows.html
* https://conemu.github.io/en/CygwinMsysConnector.html
* https://github.com/Maximus5/ConEmu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aother-wsl+
