### ISSUE TITLE
Question| Tab Bar menu

### ISSUE THREAD

**Issue by avielc** [ConEmu/ConEmu.github.io#36]
Hi, 
I'd like to remove any paths and have the user@host from my ssh connection remain in the tab bar. 
To do that, I need to use the "Skip words from Title" function on "Tab Bar" menu. 

Unfortunately I couldn't find any information on how to add patterns to it, 
Is it possible?

Thanks

**Comment by Maximus5** [comment]
Don't you run your tabs from Tasks?
I believe the proper way is name your tab on start. Than nothing tricky would be required to display that name
https://conemu.github.io/en/NewConsole.html#syntax
`-new_console:t:"user@host"`

**Comment by avielc** [comment]
Hi @Maximus5 - Thanks for replying
That would have been perfect if "user" and "host" were a permanent ones, 
But consider i'm using bash to connect to various servers and all have dynamic names\users So I need the bash to pull it out during my connection (happens using  xterm) but it also adds the path. I need to remove that path somehow

**Comment by Maximus5** [comment]
So, it would be somewhat tricky.
At the moment you may rename your tab with ANSI sequences.
Just send the string from PS1 on your server.

**Comment by avielc** [comment]
If I understood you correctly, I need to change whatever my bashrc says on the $PS1. 
No way to do some patterns on the "Skip words from Title" option in menu? (there's administrator:| there, just being able to add ":/*" would be perfect to ignore everything past "user@host"

or in short, patterns 

Eitherway Thank you again Maximus for helping, really appreciate it!
By the way Windows 10 19H1 finally fixed the line breaks on ssh, I can fully enjoy ConEmu now 
Thanks again

**Comment by Maximus5** [comment]
> would be perfect to ignore everything past "user@host"
No way. Patterns are not supported there, only **exact** strings.

You may fill a request for a tab template, I suppose it's rather easy to detect user@host from console title.
But please create an issue on the project site, not here. This one is only for documentation issues ;)

PS. I'm still waiting new Win10 build on the slow ring :(
