### ISSUE TITLE
The panel of commands

### ISSUE THREAD

**Issue by ZeoNish** [ConEmu/ConEmu.github.io#39]
Can I add a Panel with ready-made commands that I would add myself?

I use the same commands very often and I would like to write them down once for further use.

![image](https://user-images.githubusercontent.com/8596319/63668190-11190e80-c7df-11e9-834a-a08c056a44eb.png)

**Comment by Maximus5** [comment]
Please don't ask questions about the product here.
This tracker is intended **only** for documentation bugs.

Panels are not allowed. But you may create a [GuiMacro](https://conemu.github.io/en/GuiMacro.html) to print anything you want. Hotkeys are faster than mouse ;)
