### ISSUE TITLE
Failed to run WSL on ConEmu

### ISSUE THREAD

**Issue by yihuajack** [ConEmu/ConEmu.github.io#45]
According to BashOnWindows.md, I have installed feature ‘WSL support’ and ‘cygwin/msys connector’ and required files wslbridge.exe, cygwin1.dll, wslbridge-backend and conemu-cyg-64.exe should be installed into %ConEmuBaseDir%\wsl and %ConEmuBaseDir% folders. Then I modified the task command and parameter according to that document. However, it gave me an error:
```wslbridge error: failed to start backend process
note: backend error output: -v: -c: line 0: unexpected EOF while looking for matching `''
-v: -c: line 1: syntax error: unexpected end of file


ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...
```
I'm using WSL1 Ubuntu 20.04 LTS and ConEmu 200713.x64. There were no errors when I configured MSYS2 and Cygwin in ConEmu in my machine.

**Comment by Maximus5** [comment]
Hi

I don't think it's WSL1, the error looks like you have WSL2.
There is an open issue on the official issue tracker: https://github.com/Maximus5/ConEmu/issues/1930

PS. This issue tracker is intended only for documentation improvements.

**Comment by yihuajack** [comment]
It's WSL1 indeed and the error is not the same but that issue really works for this situation. Thank you anyway!
