### ISSUE TITLE
shortcut launches java app, but leaves terminal window open. before conemu it didnt leave window open

### ISSUE THREAD

**Issue by meffect** [ConEmu/ConEmu.github.io#8]
`C:\Users\[user]\IBM\ClientSolutions\Start_Programs\Windows_x86-64\acslaunch_win-64.exe`

then conemu window stays open in the background. if I close the conemu window, it closes the ibm app. 

any way to close the terminal window after it launches the app? Before I installed conemu, the default cmd would close after the app launched.

its a java app

**Comment by Maximus5** [comment]
This tracker is intended for **documentation** issues only!

**Comment by meffect** [comment]
couldnt figure out where to ask this question

**Comment by Maximus5** [comment]
https://conemu.github.io/en/Issues.html

**Comment by Maximus5** [comment]
Issue was not created in right place. Closed due to unanswered.
