### ISSUE TITLE
screen status line repeated continuously

### ISSUE THREAD

**Issue by HerveMARTIN** [ConEmu/ConEmu.github.io#9]
Just like mentionned here https://github.com/ConEmu/old-issues/issues/1051 when running a remote screen with a status bar, this bar is continuously repeated.
No problem with Cygwin terminal, just with ConEmu with a Cygwin bash (and also ConEmu with a Git bash)

Step to reproduce : 
- start a console with cygwin, connect with a cygwinbash
- connect to a remote linux server with ssh
- run a screen with a status bar
- hit enter

**Comment by Maximus5** [comment]
1. This is wrong place to report ConEmu **application** issues. Proper places are described here: http://conemu.github.io/en/Issues.html 
2. Even than, why do you think it's a ConEmu problem? I can't fix cygwin bugs, I'm not a cygwin developer our maintainer. Read carefully: http://conemu.github.io/en/ThirdPartyProblems.html

**Comment by HerveMARTIN** [comment]
Well as i said, it works just fine with Cygwin default console app but not with ConEmu... for both it's the same bash program, the only différence is the use of ConEmu.
If i go to fill an issue to cygwin, they will tell me that it's a ConEmu problem, for sure...
BTW sorry for reporting in the wrong place.

**Comment by Maximus5** [comment]
Did you read this? http://conemu.github.io/en/ThirdPartyProblems.html

**Comment by Maximus5** [comment]
> Cygwin default console app

Ambiguous
